trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npx -p semantic-release
    -p @semantic-release/git
    -p @semantic-release/npm
    -p @semantic-release/github
    semantic-release
  displayName: 'Semantic release'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
